spring.application.name=RefugioConnect

spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-dap2pp3tqb8s73f4pukg-a:5432/refugioconnect
spring.datasource.username=refugioconnect_user
spring.datasource.password=4tU71lCSYI7uoc1btv2MUjk2xy8fGFiG